"""Validated domain contracts used by ScholarTrace workflows."""

from scholartrace.schemas.algorithm import (
    AlgorithmComponent,
    AlgorithmSpec,
    CandidateExperimentPlan,
    InnovationCandidate,
    InnovationCandidateRanking,
    InnovationFinding,
    InnovationValidationReport,
    MethodDifference,
    PriorArtEntry,
    PriorArtMap,
)
from scholartrace.schemas.debug import (
    DebugCase,
    DebugCaseStatus,
    DiagnosticFinding,
    DiagnosticHypothesis,
    EvidenceRef,
    FailureCategory,
    RegressionResult,
    RepairFileChange,
    RepairProposal,
)
from scholartrace.schemas.decisions import DecisionRecord
from scholartrace.schemas.design import (
    CaptureField,
    DataCollectionProtocol,
    DesignFinding,
    DesignValidationReport,
    PipelineSpec,
    PipelineStage,
    PipelineVersionComparison,
)
from scholartrace.schemas.experiment import (
    ClaimUpdate,
    ExperimentMatrixEntry,
    ExperimentPlan,
    MetricAggregate,
    MetricResult,
    RunManifest,
)
from scholartrace.schemas.figures import (
    FigureArtifactBundle,
    FigurePoint,
    FigureSpec,
    FigureSuggestion,
    FigureValidationReport,
)
from scholartrace.schemas.literature import (
    ChunkSearchResult,
    Document,
    DocumentChunk,
    DocumentMetadata,
    EvidenceCard,
    ProjectDocument,
    SourceSpan,
)
from scholartrace.schemas.manuscript import Claim, Manuscript, SectionContract
from scholartrace.schemas.research import ResearchQuestion
from scholartrace.schemas.runner import (
    ControlledRunEvent,
    ControlledRunRecord,
    ControlledRunSpec,
    ControlledRunStatus,
    ResourceLimits,
    RunBackend,
    RunEventStream,
)
from scholartrace.schemas.tracking import DVCDataVersionCheck, TrackingAttempt

__all__ = [
    "AlgorithmComponent",
    "AlgorithmSpec",
    "CandidateExperimentPlan",
    "CaptureField",
    "ChunkSearchResult",
    "Claim",
    "ClaimUpdate",
    "ControlledRunEvent",
    "ControlledRunRecord",
    "ControlledRunSpec",
    "ControlledRunStatus",
    "DVCDataVersionCheck",
    "DataCollectionProtocol",
    "DebugCase",
    "DebugCaseStatus",
    "DecisionRecord",
    "DesignFinding",
    "DesignValidationReport",
    "DiagnosticFinding",
    "DiagnosticHypothesis",
    "Document",
    "DocumentChunk",
    "DocumentMetadata",
    "EvidenceCard",
    "EvidenceRef",
    "ExperimentMatrixEntry",
    "ExperimentPlan",
    "FailureCategory",
    "FigureArtifactBundle",
    "FigurePoint",
    "FigureSpec",
    "FigureSuggestion",
    "FigureValidationReport",
    "InnovationCandidate",
    "InnovationCandidateRanking",
    "InnovationFinding",
    "InnovationValidationReport",
    "Manuscript",
    "MethodDifference",
    "MetricAggregate",
    "MetricResult",
    "PipelineSpec",
    "PipelineStage",
    "PipelineVersionComparison",
    "PriorArtEntry",
    "PriorArtMap",
    "ProjectDocument",
    "RegressionResult",
    "RepairFileChange",
    "RepairProposal",
    "ResearchQuestion",
    "ResourceLimits",
    "RunBackend",
    "RunEventStream",
    "RunManifest",
    "SectionContract",
    "SourceSpan",
    "TrackingAttempt",
]
