"""Validated domain contracts used by ScholarTrace workflows."""

from scholartrace.schemas.algorithm import (
    AlgorithmComponent,
    AlgorithmSpec,
    CandidateExperimentPlan,
    InnovationCandidate,
    InnovationCandidateRanking,
    InnovationFinding,
    InnovationValidationReport,
    MethodDifference,
    PriorArtEntry,
    PriorArtMap,
)
from scholartrace.schemas.decisions import DecisionRecord
from scholartrace.schemas.design import (
    CaptureField,
    DataCollectionProtocol,
    DesignFinding,
    DesignValidationReport,
    PipelineSpec,
    PipelineStage,
    PipelineVersionComparison,
)
from scholartrace.schemas.experiment import (
    ClaimUpdate,
    ExperimentMatrixEntry,
    ExperimentPlan,
    MetricAggregate,
    MetricResult,
    RunManifest,
)
from scholartrace.schemas.literature import (
    ChunkSearchResult,
    Document,
    DocumentChunk,
    DocumentMetadata,
    EvidenceCard,
    ProjectDocument,
    SourceSpan,
)
from scholartrace.schemas.research import ResearchQuestion
from scholartrace.schemas.runner import (
    ControlledRunEvent,
    ControlledRunRecord,
    ControlledRunSpec,
    ControlledRunStatus,
    ResourceLimits,
    RunBackend,
    RunEventStream,
)

__all__ = [
    "AlgorithmComponent",
    "AlgorithmSpec",
    "CandidateExperimentPlan",
    "CaptureField",
    "ChunkSearchResult",
    "ClaimUpdate",
    "ControlledRunEvent",
    "ControlledRunRecord",
    "ControlledRunSpec",
    "ControlledRunStatus",
    "DataCollectionProtocol",
    "DecisionRecord",
    "DesignFinding",
    "DesignValidationReport",
    "Document",
    "DocumentChunk",
    "DocumentMetadata",
    "EvidenceCard",
    "ExperimentMatrixEntry",
    "ExperimentPlan",
    "InnovationCandidate",
    "InnovationCandidateRanking",
    "InnovationFinding",
    "InnovationValidationReport",
    "MethodDifference",
    "MetricAggregate",
    "MetricResult",
    "PipelineSpec",
    "PipelineStage",
    "PipelineVersionComparison",
    "PriorArtEntry",
    "PriorArtMap",
    "ProjectDocument",
    "ResearchQuestion",
    "ResourceLimits",
    "RunBackend",
    "RunEventStream",
    "RunManifest",
    "SourceSpan",
]
